services:
  mass-tech-server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-server
  mongodb-server:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
