name: client
on:
  workflow_dispatch:
  push:
    paths:
      - 'client/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
